---
title: 干旱胁迫下土壤真菌相关研究论文复现报告
author: 焦静雨 余虹 孙铭仪
date: 2026-05-30
format: html
---

# 一、项目概述
## 1.1 研究背景与选题依据
土壤真菌是陆地生态系统的重要组成部分，在物质循环、养分周转以及逆境适应过程中发挥关键作用。干旱是全球频发的气候胁迫因子，会显著改变土壤微生物的生理代谢与群落活性。

本次复现选取论文 *Soil fungi remain active and invest in storage compounds during drought independent of future climate conditions* 作为研究对象。该研究探究了干旱环境下土壤真菌的活性变化、储能物质积累规律，并分析未来气候条件对该响应模式的影响，对理解微生物逆境适应机制具有参考价值。

## 1.2 复现目标
1. 复现原文的核心图表，使用R语言进行数据预处理、统计分析和可视化；
2. 对比复现结果与原文结果，验证研究结论的可重复性；

## 1.3 论文基础信息
- 论文题目：Soil fungi remain active and invest in storage compounds during drought independent of future climate conditions
- 发表期刊：Nature Communications
- 研究核心：干旱胁迫下土壤真菌活性、储能物质积累及其与后续气候条件的关联性
- 数据来源：论文公开数据集

# 二、运行环境与工具准备
## 2.1 运行环境
本次复现全程在Windows系统下完成，具体环境配置如下：
- 操作系统：Windows系统
- 编程语言：R 4.5.2
- 代码编辑与运行工具：Positron

## 2.2 依赖包介绍与加载
本次分析主要使用R语言主流数据分析与可视化包，包含数据读取、清洗、统计、绘图相关工具。
```{r 环境加载, label="setup"}
## 加载核心工具包
- 主要使用的工具包包括tidyverse、dplyr、readr、ggplot2、corrplot等
本次项目文件划分清晰，各目录功能明确：
data/：存放原始实验数据文件
code/：独立 R 代码脚本
results/：代码运行生成的图表文件
readme.md：项目说明文件
report.qmd：复现结果报告

# 三、数据获取
## 3.1数据来源
本项目所用实验数据均来源于论文公开数据平台，数据获取地址：
https://www.nature.com/articles/s41467-024-54537-y

## 3.2 原始数据说明
数据集包含多组试验指标，主要字段：
- treatment：试验处理组（干旱组 / 对照组 / 不同气候梯度组）
- time：观测时间
- plfa_growth：真菌 PLFA 生长率
- soil_water：土壤含水量
- soil_resp：土壤呼吸速率

# 四、复现结果可视化
## 4.1 复现说明
本次未对论文全部图表进行复现，仅选取三张具有代表性的核心图表完成复现：
- 图1：不同处理条件下土壤真菌PLFA生长率箱线图，用于直观对比组间数据分布与差异；
- 图3：革兰氏阳性细菌、革兰氏阴性细菌、真菌类群的比生长速率，以及真菌 / 细菌生长速率比值的分组箱线图，重点对比各类微生物对干旱的响应差异；
- 图4：真菌中性脂质脂肪酸（NLFA）生成量、NLFA 与 PLFA 比值的组间箱线图，用以表征真菌在干旱胁迫下储能物质的合成与分配特征。

## 4.2 复现结果解读
- 图1：从复现的箱线图可以看出，干旱处理显著降低了土壤微生物群落的整体生长速率与呼吸速率，微生物生长速率在干旱条件下降幅接近一半；而微生物群落碳利用效率受干旱影响较小，仅在未来气候处理下恢复期出现明显下降。复现的箱线图在数据中位数、四分位分布、组间高低差异、干旱与恢复期的变化趋势上，与原文图 1 吻合。
- 图3：图表结果显示，干旱胁迫下，革兰氏阳性、革兰氏阴性细菌的比生长速率均出现显著下降，降幅接近 50%；而真菌生长速率几乎不受干旱影响，表现出极强的干旱抗性。同时，干旱条件下真菌与细菌生长速率的比值显著升高，复水恢复期后该比值回落至正常水平，且未来气候条件未改变这一响应规律。复现出的箱线图的组间差异大小、数据离散程度、各类微生物对干旱的响应趋势，与原文图 3 高度一致，精准还原了细菌易受干旱抑制、真菌稳定耐受干旱的核心试验规律。
- 图4：由复现图表可知，干旱处理下真菌 NLFA 储能物质生成量显著上升，NLFA 与 PLFA 的比值远高于常规环境，干旱期间真菌向储能化合物的碳分配比例提升数倍；进入恢复期后，真菌储能物质合成量快速回落至正常水平。同时未来气候条件会进一步放大干旱对真菌储能物质合成的促进作用。复现的箱线图的数据分布、组间差异显著性、干旱-恢复期的变化趋势，与原文图 4 匹配，复现了干旱促进真菌积累储能物质、复水后快速恢复常态的关键研究结果。

# 五、局限性及总结
## 局限性
本次只完成图 1、图 3、图 4三张核心箱线图复现，未对论文全部附图、补充图及所有统计检验进行完整复现

## 总结
本次复现，将文字说明、运行结果、图表整合，实现结果可复现、内容可追溯，验证了所选论文研究结果的可靠性。
